[world]
name = "Golem Runner"
description = "Golem Runner is a mobile endless runner game where players control elemental golems. Built using Dojo Engine and Cartridge Controller on Starknet."
website = "https://github.com/AkatsukiLabs/GolemRunner"
seed = "golem_runner"

[namespace]
default = "golem_runner"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"golem_runner" = ["golem_runner-game"]
"golem_runner-TrophyCreation" = ["golem_runner-game"]
"golem_runner-TrophyProgression" = ["golem_runner-game"]