[world]
name = "Golem Runner"
description = "Golem Runner is a mobile endless runner game where players control elemental golems. Built using Dojo Engine and Cartridge Controller on Starknet."
website = "https://github.com/AkatsukiLabs/GolemRunner"
seed = "golem_runner5"

[namespace]
default = "golem_runner"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"

[writers]
"golem_runner" = ["golem_runner-game"]
"golem_runner-TrophyCreation" = ["golem_runner-game"]
"golem_runner-TrophyProgression" = ["golem_runner-game"]