# The World address to index.
world_address = "0x01fe4f3da25325886ab8c89826d0af42385e36f2cdb717441532e3220d179da4"
 
# Default RPC URL configuration
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

# Indexing Options
[indexing]
allowed_origins = ["*"]
transactions = true
pending = true
polling_interval = 1000
contracts = []

[events]
raw = true

[sql]
historical = ["golem_runner-TrophyProgression"] 